### ISSUE TITLE
Consider putting tiling on melpa

### ISSUE THREAD

**Issue by colonelpanic8** [lgfang/tiling#1]
Hey, I think it would be cool to put your tiling package on melpa where it could get exposure and benefit from community maintenance. What do you think?

**Comment by lgfang** [comment]
Glad you liked it. Maybe I'll give it a try. But, not sure when will I find time to tidy up my code so that I can submit pull request.

**Comment by colonelpanic8** [comment]
I actually just did a rewrite and requrested that it be added to melpa

https://github.com/IvanMalison/tile

https://github.com/melpa/melpa/pull/4388

**Comment by lgfang** [comment]
Cool. Will refer people to your repo. I guess you need to clone melpa repo to submit pull request. Right?

**Comment by lgfang** [comment]
Cool. Will refer people to your repo.
